# Generated by Django 4.2 on 2023-04-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teachers",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("is_teacher", models.BooleanField()),
            ],
        ),
    ]
